#!/bin/bash
IP= "10.140.11.1"

backupfolder="/var/www/harona/logs/"

logfile="$backupfolder/"backup_log.txt


echo "subject: Test end-to-end connectivity   $(date +'%d-%m-%Y %H:%M:%S')" >> "email2.txt"
echo "to: <mailto@gmail.com>" >> "email2.txt"
echo "Dear, sir  " >>  "email.txt"
ping -c 3 10.140.11.1  > /dev/null
if [ $? != 0 ]
then
IP= "10.140.11.171"
echo "The destination service (local IP [ $IP ] )site seems to be down  at  $(date +'%d-%m-%Y %H:%M:%S')"  >> "$logfile"
echo "Your Service (local [ $IP ] )site seems to be down" >> "email2.txt"
echo "The destination service is not responding! Please check the local system is standby and ready to  receive backup files  " >>  "email2.txt"
echo "Regards, " >>  "email2.txt"
echo "Admin" >>  "email2.txt"
echo "This is autogenerated email, Please donot reply!" >>  "email2.txt"
curl --url 'smtps://smtp.gmail.com:465' --ssl-reqd \
 --mail-from 'mailfrom@gmail.com' --mail-rcpt 'emailto@gmail.com' \ 
 --upload-file email2.txt  --user 'mailfrom@gmail.com:password' --insecure

fi
rm -r email2.txt
